### ISSUE TITLE
请问怎么换“启用距离指示”那个圆圈的颜色啊？

### ISSUE THREAD

**Issue by tonyqr** [harytfw/GlitterDrag#145]
是在选项的样式里边吗？改了几个color好像没起作用呢？
![图片](https://user-images.githubusercontent.com/35569714/176148511-78833ad9-4f94-4285-a3ab-166ab7602ad5.png)

**Comment by harytfw** [comment]
先在 “通用” 里面 打开 “启用自定义样式”
然后在样式页面，清空原有的css，输入以下的css。
```css
#GDIndicator {
    position: absolute !important;
    z-index: 2147483601 !important;
    /*由js控制*/
    border-radius: 0px !important;
    border-style: dashed !important;
   /*修改颜色*/
    border-color: red !important;
}
```
点击下方的保存，刷新网页的页面生效。
